# Generated by Django 4.0.4 on 2022-04-30 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abuelos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('paisDeNac', models.CharField(max_length=30)),
                ('anioDeNac', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Hermanos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('paisDeNac', models.CharField(max_length=30)),
                ('anioDeNac', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Padres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('paisDeNac', models.CharField(max_length=30)),
                ('anioDeNac', models.IntegerField()),
            ],
        ),
    ]
